title: My Terminal Blog
description: notes
url: "https://mrurbo.github.io"
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-seo-tag
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
