title: My Blog
description: notes
url: "https://<your-user>.github.io"
theme: minima # or remove and use your own layouts below
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-seo-tag
permalink: /:categories/:year/:month/:day/:title/
# if you want a custom collection instead of _posts, see section 3
